name: Auto Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_IP: ${{ secrets.HOSTINGER_IP }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}

        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOSTINGER_IP >> ~/.ssh/known_hosts

<<<<<<< HEAD
      - name: Publish Build to Another Branch
        uses: s0/git-publish-subdir-action@develop
        with:
          branch: develop
          folder: build  # <-- CHANGE THIS IF YOUR BUILD OUTPUT IS IN A DIFFERENT FOLDER
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Build: ({sha}) {msg}"
=======
          # SSH into Hostinger and deploy
          ssh $HOSTINGER_USER@$HOSTINGER_IP << 'EOF'
            cd $PROJECT_PATH
            git pull origin develop
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            php artisan queue:restart
          EOF
>>>>>>> 77bfa228558eae2672c63c944c9d9ff611439bf3
