name: Generate a build and push to another branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Publish Build to Another Branch
        uses: s0/git-publish-subdir-action@develop
        with:
          REPO: self  # Must specify the repo
          branch: develop
          folder: build  # <-- CHANGE THIS IF YOUR BUILD OUTPUT IS IN A DIFFERENT FOLDER
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Build: ({sha}) {msg}"
