name: Generate a build and push to another branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Publish Build to Another Branch
        uses: s0/git-publish-subdir-action@master  # Use "master" instead of "develop"
        with:
          repo: self  # Specify "self" to use the current repo
          branch: build  # Push to "build" branch
          folder: public/build  # Make sure this is your correct build output folder
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Build: ({sha}) {msg}"
